
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import core

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def login():
    user = entry_1.get()
    password = entry_2.get()
    core.login(user,password)

def scroll():
    pass


window = Tk()

window.geometry("1280x550")
window.configure(bg = "#AEACAC")


canvas = Canvas(
    window,
    bg = "#AEACAC",
    height = 550,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    68.0,
    640.0,
    550.0,
    fill="#ADAAAA",
    outline="")

canvas.create_rectangle(
    640.0,
    68.0,
    1280.0,
    550.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1280.0,
    34.0,
    fill="#3B2A6A",
    outline="")

canvas.create_rectangle(
    0.0,
    34.0,
    1280.0,
    68.0,
    fill="#7C3C9A",
    outline="")

canvas.create_text(
    84.0,
    96.0,
    anchor="nw",
    text="Description about software",
    fill="#502F60",
    font=("Roboto Bold", 20 * -1)
)

canvas.create_text(
    538.0,
    8.0,
    anchor="nw",
    text="ImageDownloadTool",
    fill="#FFFFFF",
    font=("Roboto Bold", 20 * -1)
)

canvas.create_text(
    661.0,
    96.0,
    anchor="nw",
    text="Login",
    fill="#4F2E5F",
    font=("Roboto Bold", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    980.5,
    193.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_1.place(
    x=842.0,
    y=170.0,
    width=277.0,
    height=45.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    980.5,
    261.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_2.place(
    x=842.0,
    y=238.0,
    width=277.0,
    height=45.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    980.5,
    329.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_3.place(
    x=842.0,
    y=306.0,
    width=277.0,
    height=45.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    980.5,
    397.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_4.place(
    x=842.0,
    y=374.0,
    width=277.0,
    height=45.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login(),
    relief="flat"
)
button_1.place(
    x=1158.0,
    y=453.0,
    width=90.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=34.0,
    width=60.0,
    height=34.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=60.0,
    y=34.0,
    width=60.0,
    height=34.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=120.0,
    y=34.0,
    width=60.0,
    height=34.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=180.0,
    y=34.0,
    width=60.0,
    height=34.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1158.0,
    y=377.0,
    width=90.0,
    height=40.0
)

canvas.create_text(
    735.0,
    170.0,
    anchor="nw",
    text="User ID",
    fill="#000000",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_text(
    734.0,
    240.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_text(
    734.0,
    306.0,
    anchor="nw",
    text="Profile",
    fill="#000000",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_text(
    734.0,
    374.0,
    anchor="nw",
    text="Path",
    fill="#000000",
    font=("Roboto Bold", 18 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    307.0,
    271.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
